import Head from "next/head";
import styles from "../styles/Home.module.css";
import Board from "../components/Board";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zero Hash Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Board></Board>
    </div>
  );
}
